-- table_1 : 42000 [-100 ; 100]
-- table_2 : 60 [500 ; 5000]
EXPLAIN (ANALYZE) SELECT count(*) FROM table_1 t1, table_2 t2 WHERE t1.r && t2.r; -- JOIN CARDINALITY ESTIMATION
EXPLAIN (ANALYZE) SELECT count(*) FROM table_1 t1 WHERE t1.r && int4range(-26, 44); -- RESTRICTION SELECTIVITY OVERLAP ESTIMATION
EXPLAIN (ANALYZE) SELECT count(*) FROM table_1 t1 WHERE t1.r << int4range(-26, 44); -- RESTRICTION SELECTIVITY STRICTLY LEFT ESTIMATION
